#+TITLE: Learning Org mode

* Resources

- The Org mode manual: https://orgmode.org/org.html.
- Collection of other useful links https://orgmode.org/worg/.
- Rainer König's org mode presentations on YouTube at
  https://www.youtube.com/playlist?list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE.
- Derek Taylor's /Org Mode Basics In Doom Emacs/ video on YouTube: https://youtu.be/34zODp_lhqg.

* Org for GDT

Resources:
- A collection of links related to Org for GTD:
  https://orgmode.org/worg/org-gtd-etc.html.
- A Reddit thread with some useful comments and links to other resources:
  https://www.reddit.com/r/emacs/comments/i09ncw/discussion_using_emacsorgmode_to_manage_life/.
- Nicolas Petton's /Orgmode for GTD/:
  https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html.
- Tasshin Fogleman's /Plan Your Day: Daily Time Management with Emacs, Org-Mode,
  and Google Calendar/.
  https://tasshin.com/blog/plan-your-day-daily-time-management-with-emacs-org-mode-and-google-calendar/
- Charles Cave's /How I use Emacs and Org-mode to implement GTD/:
  http://members.optusnet.com.au/~charles57/GTD/gtd_workflow.html
- Jethro Kuan's /Org-mode Workflow/:
  https://blog.jethro.dev/posts/org_mode_workflow_preview/.


** Getting things done general resources

- Erlend Hamburg's /GTD in 15 minutes - A Pragmatic Guide to Getting Things
  Done/: https://hamberg.no/gtd.

Maybe?
 - https://lifehacker.com/productivity-101-a-primer-to-the-getting-things-done-1551880955
 - https://joshkaufman.net/getting-things-done/

* Doom keybindings

To see the full list of keybindings, as usual you can use =describe-mode= (=C h
m=).

It is worth noting that the usual outline commands such as =outline-promote= and
=outline-demote= (and found in the =g= prefix) are remapped to Org mode specific
commands.

- Prefix keys
  - =SPC m= prefixes Org-specific bindings.
  - =z= has additional commands.
  - =g= has outline movements such as =g j= and =g k=.
- Top-level bindings
  - =C-return= to add a header or item (context-sensitive) at the current level.
  - =M-return= to add a header at the current level.
  - =C-k= and =C-j= to move up/down the headers at the same level.
  - =M-h= and =M-l= to promote/demote headers or list elements.
  - =M-k= and =M-j= to move up/down headers or list elements.
  - =M-K= and =M-J= to move up/down a single header or list element.
  - =v a e= and =d a e= to select/delete an element.
  - =v a R= and =d a R= to select/delete a subtree.
  - =S-<left>= or =S-<right>= (i.e. shift left/right arrow) toggles to-do items.
    Alternatively, you can use the =SPC m t= prefix to add a to-do state.


* Rainer König's org mode presentations on YouTube

When in org-mode, the usual mode-specific top-level prefix is =SPC m=.

** EO1S03: Schedule, deadline, and agenda view

See https://www.youtube.com/watch?v=IofHvutUWV0&list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE&index=3&t=3s.

Use =SPC m d= to activate the date/deadline prefix.

- =SPC m d s= (=org-schedule=) invokes a pop-up buffer with a calendar
  representation that allows you to schedule a start date for your item. Using
  the =C-h=, =C-j=, =C-k=, and =C-l= keys allows you to navigate the calendar,
  and you can press enter to pick a date.
- =SPC m d d= invokes a pop-up calendar buffer as with =org-schedule=, but for a
  deadline date instead.
- =SPC n a= or =SPC o A= or =SCP o a a= (=org-agenda=) invokes a pop-up that
  allows you to view a agenda or list of =TODO= items.


** E01S04: Repeating tasks

This video is about scheduling recurring tasks, such as for example adding a
weekly task to mow the lawn. In the timestamp field you can add a so-called
repeater element that might look like e.g. =+1m=, with the meaning that the task
has is intended to be completed every 1-month interval after the original date.

There are other forms for the repeater element. One is a form such as e.g.
=++1m= which means that if a task is overdue by multiple scheduled events and
you complete the task, that the next scheduled task is moved forward enough to
be in the future. Another is a form such as e.g. =.+1m= which means that if a
task is completed then another task is scheduled one week after the completion
date.

*** Relevant links:

- Rainer's video: https://www.youtube.com/watch?v=nbC-gL5wcf4&list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE&index=4.
- The Org Manual Repeated Tasks: https://orgmode.org/manual/Repeated-tasks.html.

** E01S05: Checklists

This video is about checkboxes, which allow you to essentially add a radio
button (i.e. a toggle) to a list item indicating whether the item has been
completed. As noted in the Org manual, checkboxes are similar to TODO items but
are aren't included in the global TODO list, which makes them convenient to use
to split a task into a number of smaller steps.

- A given item in a list can be made into a checkbox item by adding =[ ]= after
  the list starting string (e.g. =- [ ]= or =1. [ ]=). Use =SPC u g r= to toggle
  the presence of a checkbox.
- If the item is completed then you can mark a given checkbox as completed by
  replacing =[ ]= with e.g. =[-]= or =[X]=. Use =g r= to toggle the completion
  state of a given checkbox.
- Place =[/]= or =[%]= before a list to obtain a running tally indicating how
  many tasks have been completed in a list. The former gives you a count such as
  e.g. =[2/4]=, while the latter gives you a percentage such as =[50%]=

*** Relevant links:

- Rainer's video: https://www.youtube.com/watch?v=gvgfmED8RD4&list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE&index=5.
- The Org Manual Checkboxes: https://orgmode.org/manual/Checkboxes.html.

** E02S01: Tags

This video is about tags, which are a mechanism for assigning labels to
headlines that can then be used to create cross-reference information according
to their tags (recall that headlines are what Org calls the lines starting with
=*=, =**=, etc. that define the document sections and subsections).

- The tags are creating by placing a word surrounded by colons such as =:work:=
  at the end of a headline.
- Multiple tags take the form =:work:urgent:=.
- Tags are inherited hierarchically (a child section recursively inherits tags
  from its parent).
- Use =SPC m q= (=counsel-org-tag=) to create a tag. Note that the interface
  provided by the =counsel-org-tag= is different than the one shown in the
  video.
  - You can build up a collection of tags through multiple invocations of
    =counsel-org-tag=.
  - Select a tag that is already part of the headline definition to remove it.
  - Use =C-M-m= to make multiple selections (see the link below for more
    details).

*** Relevant links:

- Rainer's video: https://youtu.be/GcUVvlClo9k.
- The Org Manual Tags: https://orgmode.org/manual/Tags.html.
- Swiper key bindings for multiple selections and actions: http://oremacs.com/swiper/#key-bindings-for-multiple-selections-and-actions-keep-minibuffer-open.
